### ISSUE TITLE
Home assistant autodiscovery not working - 0.7.0 

### ISSUE THREAD

**Issue by mishomvp** [HASwitchPlate/openHASP#421]
## Version of the custom_component

0.7.0 

## Describe the bug
The home assistant does not detect the display that I have connected using MQTT.  
Model: wt32-sc01-plus_8MB 
OpenHASP version: 0.6.4-dev a4f1fdd
Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230110.0 - latest
Mosquitto broker - 6.1.3 (home assistant add-on) - protocol version 5 (but with 3 is the same)
 I checked the communication between MQTT and the display. Everything is fine. Through MQTT Explorer everything seems fine.
But I don't see it in it doesn't appear in devices and services.
I have several other devices that communicate via MQTT without issue.
I was only able to see this error when calling OpenHASP from Devices and services.
If there is anything else I need to do to resolve a problem, I am available.
Thanks in advance!

## Debug log

```text

2023-01-28 19:08:51.301 INFO (MainThread) [custom_components.openhasp.config_flow] Discovery Only
2023-01-28 19:08:53.464 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 154, in async_wrapper
    await async_func(*args)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/discovery.py", line 306, in async_integration_message_received
    result = await hass.config_entries.flow.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 229, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 256, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 374, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/openhasp/config_flow.py", line 89, in async_step_mqtt
    _discovered = json.loads(discovery_info.payload)
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 1 column 141 (char 140)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 156, in async_wrapper
    log_exception(format_err, *args)
  File "/usr/src/homeassistant/homeassistant/util/logging.py", line 115, in log_exception
    friendly_msg = format_err(*args)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/client.py", line 243, in <lambda>
    f"Exception in {msg_callback.__name__} when handling msg on "
AttributeError: 'functools.partial' object has no attribute '__name__'


```

**Comment by fvanroie** [comment]
This should be fixed in [the latest build](https://github.com/HASwitchPlate/openHASP/actions/runs/4033807633)

**Comment by mishomvp** [comment]
Yes! Thank you!
I confirm. I installed the latest version and the home assistant immediately found the display.
